---
- name: install packages
  yum: name="{{item}}" state=installed
  with_items:
    - python-setuptools
    - fuse
    - jsvc
    - libxml2

- name: install sdfs
  shell: rpm -ivh --force http://www.opendedup.org/downloads/sdfs-3.2.4-1.x86_64.rpm

- lineinfile: dest=/etc/security/limits.conf state=present
            line='* hardnofile 65535'
- lineinfile: dest=/etc/security/limits.conf state=present
            line='* soft nofile 65535'
