---
- hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  tasks:
  - name: update system
    yum: name=* state=latest
  roles:
    - openjdk
    - tomcat8
    - opendedup
    - copycat
    - maven
    - nodejs
    - nginx
    - awslogs
    - logrotate
    - fio
